version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: SportStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=SportStore;Username=postgres;Password=YourStrongPassword
    ports:
      - "8080:80"
    restart: on-failure

volumes:
  pgdata:
